# Generated by Django 3.1.1 on 2020-09-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='snack',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
